package protocol;

public enum MessageType {
    CONNECT, DISCONNECT, TEXT, SERVER_INFO, USER_LIST,
    JOIN_ROOM, LEAVE_ROOM, ROOM_LIST, ROOM_LIST_REQ,
    PRIVATE_MSG,
    FILE_META, FILE_DATA, FILE_ACK,
    FILE_COMPLETE_IMG, FILE_COMPLETE_TXT, FILE_COMPLETE_OTHER,
    STATUS_CHANGE,
    NICK_CHANGE,
    INVITE_USER,
    PSEUDO_TAKEN,
    HISTORY
}
